# Application config
spring:
  profiles:
    active: mock
  application:
    name: portfolio-tracker-service
  web:
    resources:
      static-locations: # required to enable reload ( for development )
        - 'file:src/main/resources/public/'
        - 'classpath:/public/'
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
alpaca:
  api:
    key: ${env.ALPACA_API_KEY}
    secret: ${env.ALPACA_API_SECRET}

---
spring:
  config:
    activate:
      on-profile: mock
  data:
    jpa:
      repositories:
        enabled: false
