# Application config
spring:
  profiles:
    active: mock
  application:
    name: portfolio-tracker-service
  web:
    resources:
      static-locations: # required to enable reload ( for development )
        - 'file:src/main/resources/public/'
        - 'classpath:/public/'
  # OAuth2 settings
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: ${env.GITHUB_OAUTH_REDIRECT_URL:{baseUrl}/login/oauth2/code/github}
            clientId: ${env.GITHUB_CLIENT_ID}
            clientSecret: ${env.GITHUB_CLIENT_SECRET}

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs


alpaca:
  api:
    key: ${env.ALPACA_API_KEY:false}
    secret: ${env.ALPACA_API_SECRET:false}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: mock
  data:
    jpa:
      repositories:
        enabled: false
