# Application config
spring:
  profiles:
    active: mock
  application:
    name: portfolio-tracker-service
  web:
    resources:
      static-locations:
        - 'file:src/main/resources/public/'
        - 'classpath:/public/'
#  web:
#    resources:
#      static-locations[0]: 'file:src/main/resources/public/'
#      static-locations[1]: 'classpath:/public/'
springfox:

  documentation:
    swagger:
      v2:
        path: /api-docs

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: mock
  data:
    jpa:
      repositories:
        enabled: false
