# Application config
spring:
  profiles:
    active: mock
  application:
    name: portfolio-tracker-service
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs