swagger: '2.0'
info:
  version: '1.0'
  title: Portfolio Tracking Service
  description: Portfolio Tracking Service
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
# host: 'localhost:8080'
basePath: /api
tags:
  - name: portfolio
    description: Portfolio Controller
paths:
  /portfolio:
    get:
      tags:
        - portfolio
      summary: Retrieve Portfolio
      operationId: getPortfolio
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Portfolio'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /trades/{stock}:
    get:
      tags:
        - trades
      summary: Trade history by stock
      operationId: getTradeHistory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: stock
          description: stock name
          in: path
          required: true
          type: string
        - name: page
          description: page number
          in: query
          required: false
          type: number
          default: 1
        - name: limit
          description: limit number of history records
          in: query
          required: false
          type: number
          default: 10
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Trade'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false

definitions:
  Portfolio:
    type: object
    properties:
      holdings:
        type: array
        items:
          $ref: '#/definitions/Holding'
      purchases:
        type: array
        description: Recent Purchases
        items:
          $ref: '#/definitions/Trade'
      liquidations:
        type: array
        description: Recent Liquidations
        items:
          $ref: '#/definitions/Trade'
      summary:
        type: object
        properties:
          purchasePrice:
            type: number
          value:
            type: number
          delta:
            type: number
    title: Portfolio

  Holding:
    type: object
    properties:
      stock:
        type: string
        description: Stock name
      avgPrice:
        type: number
        description: Average Stock price at the time of purchase
      currentPrice:
        type: number
        description: Current Stock price
      amount:
        type: number
        description: Total amount of stocks in current portfolio
      value:
        type: number
        description: Value of stocks
    title: Holding

  Trade:
    type: object
    properties:
      timestamp:
        type: string
        description: Date/Time of the transaction
      stock:
        type: string
        description: Stock name
      direction:
        type: string
        enum: [ buy, sell ]
        description: >
          Trade direction:
           * `buy` - Stock purchase ( buy )
           * `sell` - Stock liquidation ( sell )
      price:
        type: number
        description: Stock price
      quantity:
        type: number
        description: Amount of stocks traded
      value:
        type: number
        description: Total dollar value of stocks traded ( quantity * price )